version: '3'
networks:
  net:
    driver: bridge

services:
  aluno-mysql:
    container_name: aluno-mysql
    image: mysql/mysql-server:5.7
    environment:
      MYSQL_DATABASE: aluno
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_ROOT_HOST: '%'
      MYSQL_USER: mysql
      MYSQL_PASSWORD: mysql123
    ports:
      - "3306:3306"
    networks:
      - net
    restart: always

  aluno:
    restart: always
    #image: hodestito/fiapcard_aluno
    build: ./Aluno
    ports:
      - "8080:8080"
    networks:
      - net
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://aluno-mysql:3306/aluno?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
      SPRING_DATASOURCE_USERNAME: mysql
      SPRING_DATASOURCE_PASSWORD: mysql123
      SERVER_PORT: 8080
    depends_on:
      - aluno-mysql