spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    #url: jdbc:mysql://localhost:3306/aluno?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    #username: root
    #password: mysql
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
